version: '3'

volumes:
  pg_data:
  static:
  static_frontend:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: zinvas/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: zinvas/foodgram_frontend
    volumes:
      - static_frontend:/app/result_build/
  nginx:
    image: zinvas/foodgram_gateway
    env_file: .env
    ports:
      - 5000:80
    volumes:
      - static:/static_django/
      - media:/media/
      - static_frontend:/static_frontend/
    depends_on:
      - backend
