# Generated by Django 4.2.11 on 2024-03-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(max_length=200),
        ),
    ]
